//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HideMyWindows.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HideMyWindows.App.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About HideMyWindows.
        /// </summary>
        public static string AboutHideMyWindows {
            get {
                return ResourceManager.GetString("AboutHideMyWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new entry.
        /// </summary>
        public static string AddNewEntry {
            get {
                return ResourceManager.GetString("AddNewEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new rule.
        /// </summary>
        public static string AddNewRule {
            get {
                return ResourceManager.GetString("AddNewRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        public static string AnErrorOccurred {
            get {
                return ResourceManager.GetString("AnErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse path.
        /// </summary>
        public static string BrowsePath {
            get {
                return ResourceManager.GetString("BrowsePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your installation of HideMyWindows is corrupt.
        /// </summary>
        public static string CorruptInstallation {
            get {
                return ResourceManager.GetString("CorruptInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like your installation of HideMyWindows is corrupt. You are missing an important file that is needed for the application to run properly.
        ///File path: {0}
        ///Consider reinstalling the application to ensure its correct functionality..
        /// </summary>
        public static string CorruptInstallationMissingFileText {
            get {
                return ResourceManager.GetString("CorruptInstallationMissingFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop preview.
        /// </summary>
        public static string DesktopPreview {
            get {
                return ResourceManager.GetString("DesktopPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show this dialog again.
        /// </summary>
        public static string DontShowThisDialogAgain {
            get {
                return ResourceManager.GetString("DontShowThisDialogAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit entry.
        /// </summary>
        public static string EditEntry {
            get {
                return ResourceManager.GetString("EditEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter value.
        /// </summary>
        public static string FilterValue {
            get {
                return ResourceManager.GetString("FilterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and hide.
        /// </summary>
        public static string FindAndHide {
            get {
                return ResourceManager.GetString("FindAndHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and hide a running process.
        /// </summary>
        public static string FindAndHideARunningProcess {
            get {
                return ResourceManager.GetString("FindAndHideARunningProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find by click.
        /// </summary>
        public static string FindByClick {
            get {
                return ResourceManager.GetString("FindByClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functionality.
        /// </summary>
        public static string Functionality {
            get {
                return ResourceManager.GetString("Functionality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can reopen this guide anytime from the &apos;About HideMyWindows&apos; tab in the settings..
        /// </summary>
        public static string Guide_AllSetText {
            get {
                return ResourceManager.GetString("Guide_AllSetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All set.
        /// </summary>
        public static string Guide_AllSetTitle {
            get {
                return ResourceManager.GetString("Guide_AllSetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your app is already running, you can always select it here and hide it!.
        /// </summary>
        public static string Guide_AlreadyRunningText {
            get {
                return ResourceManager.GetString("Guide_AlreadyRunningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your app is already running?.
        /// </summary>
        public static string Guide_AlreadyRunningTitle {
            get {
                return ResourceManager.GetString("Guide_AlreadyRunningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using &apos;Window rules&apos;, you can make it so HideMyWindows automatically detects starting apps and windows, and immediately hides them!.
        /// </summary>
        public static string Guide_AutoHideText {
            get {
                return ResourceManager.GetString("Guide_AutoHideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to hide your app automatically?.
        /// </summary>
        public static string Guide_AutoHideTitle {
            get {
                return ResourceManager.GetString("Guide_AutoHideTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To quickly select your app, press this button, then click on your app! It will automatically be selected by HideMyWindows..
        /// </summary>
        public static string Guide_CantFindText {
            get {
                return ResourceManager.GetString("Guide_CantFindText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find it?.
        /// </summary>
        public static string Guide_CantFindTitle {
            get {
                return ResourceManager.GetString("Guide_CantFindTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you really can&apos;t find your app, or you need finer control over the selection, here you can easily filter all the apps and find the ones you are looking for!.
        /// </summary>
        public static string Guide_FinerControlText {
            get {
                return ResourceManager.GetString("Guide_FinerControlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need finer control?.
        /// </summary>
        public static string Guide_FinerControlTitle {
            get {
                return ResourceManager.GetString("Guide_FinerControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter based on the process name, window name, window class, or process ID. Once a new window matches your criteria, it will automatically be hidden!.
        /// </summary>
        public static string Guide_ManyFilteringOptionsText {
            get {
                return ResourceManager.GetString("Guide_ManyFilteringOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many filtering options!.
        /// </summary>
        public static string Guide_ManyFilteringOptionsTitle {
            get {
                return ResourceManager.GetString("Guide_ManyFilteringOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the &apos;Quick launch&apos; page you can add apps that you often need to launch hidden, so you always have them ready!.
        /// </summary>
        public static string Guide_QuickLaunchOftenText {
            get {
                return ResourceManager.GetString("Guide_QuickLaunchOftenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the same app very often?.
        /// </summary>
        public static string Guide_QuickLaunchOftenTitle {
            get {
                return ResourceManager.GetString("Guide_QuickLaunchOftenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopen the guide.
        /// </summary>
        public static string Guide_Reopen {
            get {
                return ResourceManager.GetString("Guide_Reopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just click on the icon and your app will open, already hidden! Right click to edit or remove the entry..
        /// </summary>
        public static string Guide_SimpleAndQuickText {
            get {
                return ResourceManager.GetString("Guide_SimpleAndQuickText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple and quick!.
        /// </summary>
        public static string Guide_SimpleAndQuickTitle {
            get {
                return ResourceManager.GetString("Guide_SimpleAndQuickTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to start a hidden application, you can do it here!
        ///Choose the path, and the arguments if needed, and press the launch button!.
        /// </summary>
        public static string Guide_StartHereText {
            get {
                return ResourceManager.GetString("Guide_StartHereText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start here!.
        /// </summary>
        public static string Guide_StartHereTitle {
            get {
                return ResourceManager.GetString("Guide_StartHereTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your app!.
        /// </summary>
        public static string Guide_TempQuickLaunchEntryName {
            get {
                return ResourceManager.GetString("Guide_TempQuickLaunchEntryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the settings page you can change various options, such as hiding HideMyWindows itself, its tray icon, or whether it should minimize to the tray..
        /// </summary>
        public static string Guide_TweakSettingsText {
            get {
                return ResourceManager.GetString("Guide_TweakSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to tweak something?.
        /// </summary>
        public static string Guide_TweakSettingsTitle {
            get {
                return ResourceManager.GetString("Guide_TweakSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ll give you a short tour of HideMyWindows and teach you how to use it..
        /// </summary>
        public static string Guide_WelcomeText {
            get {
                return ResourceManager.GetString("Guide_WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string Guide_WelcomeTitle {
            get {
                return ResourceManager.GetString("Guide_WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide a running process.
        /// </summary>
        public static string HideARunningProcess {
            get {
                return ResourceManager.GetString("HideARunningProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide process.
        /// </summary>
        public static string HideProcess {
            get {
                return ResourceManager.GetString("HideProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide process windows.
        /// </summary>
        public static string HideProcessWindows {
            get {
                return ResourceManager.GetString("HideProcessWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide this app automatically.
        /// </summary>
        public static string HideThisAppAutomatically {
            get {
                return ResourceManager.GetString("HideThisAppAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide tray icon.
        /// </summary>
        public static string HideTrayIcon {
            get {
                return ResourceManager.GetString("HideTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide window.
        /// </summary>
        public static string HideWindow {
            get {
                return ResourceManager.GetString("HideWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is how others will see your screen..
        /// </summary>
        public static string HowOthersWillSeeYourScreen {
            get {
                return ResourceManager.GetString("HowOthersWillSeeYourScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to tray icon.
        /// </summary>
        public static string MinimizeToTrayIcon {
            get {
                return ResourceManager.GetString("MinimizeToTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing permissions.
        /// </summary>
        public static string MissingPermissions {
            get {
                return ResourceManager.GetString("MissingPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (can be left empty).
        /// </summary>
        public static string Name_CanBeLeftEmpty {
            get {
                return ResourceManager.GetString("Name_CanBeLeftEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to run HideMyWindows as administrator to use the WMI Process Trace process watcher..
        /// </summary>
        public static string NeedAdminForWMIProcessTraceProcessWatcher {
            get {
                return ResourceManager.GetString("NeedAdminForWMIProcessTraceProcessWatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No process found.
        /// </summary>
        public static string NoProcessFound {
            get {
                return ResourceManager.GetString("NoProcessFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings folder.
        /// </summary>
        public static string OpenSettingsFolder {
            get {
                return ResourceManager.GetString("OpenSettingsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistent (re-apply automatically).
        /// </summary>
        public static string Persistent {
            get {
                return ResourceManager.GetString("Persistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string Personalization {
            get {
                return ResourceManager.GetString("Personalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        public static string Primary {
            get {
                return ResourceManager.GetString("Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process arguments.
        /// </summary>
        public static string ProcessArguments {
            get {
                return ResourceManager.GetString("ProcessArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process ID.
        /// </summary>
        public static string ProcessId {
            get {
                return ResourceManager.GetString("ProcessId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process name.
        /// </summary>
        public static string ProcessName {
            get {
                return ResourceManager.GetString("ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process path.
        /// </summary>
        public static string ProcessPath {
            get {
                return ResourceManager.GetString("ProcessPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process watcher delay (in milliseconds).
        /// </summary>
        public static string ProcessWatcherDelay_InMilliseconds {
            get {
                return ResourceManager.GetString("ProcessWatcherDelay_InMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process watching method.
        /// </summary>
        public static string ProcessWatchingMethod {
            get {
                return ResourceManager.GetString("ProcessWatchingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick launch.
        /// </summary>
        public static string QuickLaunch {
            get {
                return ResourceManager.GetString("QuickLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex matches.
        /// </summary>
        public static string RegexMatches {
            get {
                return ResourceManager.GetString("RegexMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule re-apply interval (in milliseconds).
        /// </summary>
        public static string RuleReapplyInterval_InMilliseconds {
            get {
                return ResourceManager.GetString("RuleReapplyInterval_InMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run a hidden process.
        /// </summary>
        public static string RunAHiddenProcess {
            get {
                return ResourceManager.GetString("RunAHiddenProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run hidden process.
        /// </summary>
        public static string RunHiddenProcess {
            get {
                return ResourceManager.GetString("RunHiddenProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save entries.
        /// </summary>
        public static string SaveEntries {
            get {
                return ResourceManager.GetString("SaveEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save rules.
        /// </summary>
        public static string SaveRules {
            get {
                return ResourceManager.GetString("SaveRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        public static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show this app in the taskbar.
        /// </summary>
        public static string ShowThisAppInTheTaskbar {
            get {
                return ResourceManager.GetString("ShowThisAppInTheTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String contains.
        /// </summary>
        public static string StringContains {
            get {
                return ResourceManager.GetString("StringContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String ends with.
        /// </summary>
        public static string StringEndsWith {
            get {
                return ResourceManager.GetString("StringEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String equals.
        /// </summary>
        public static string StringEquals {
            get {
                return ResourceManager.GetString("StringEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String starts with.
        /// </summary>
        public static string StringStartsWith {
            get {
                return ResourceManager.GetString("StringStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To apply these settings, save the settings and restart the application.
        /// </summary>
        public static string ToApplyTheseSettingsSaveAndRestart {
            get {
                return ResourceManager.GetString("ToApplyTheseSettingsSaveAndRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhide process.
        /// </summary>
        public static string UnhideProcess {
            get {
                return ResourceManager.GetString("UnhideProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhide process windows.
        /// </summary>
        public static string UnhideProcessWindows {
            get {
                return ResourceManager.GetString("UnhideProcessWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhide tray icon.
        /// </summary>
        public static string UnhideTrayIcon {
            get {
                return ResourceManager.GetString("UnhideTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhide window.
        /// </summary>
        public static string UnhideWindow {
            get {
                return ResourceManager.GetString("UnhideWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown monitor.
        /// </summary>
        public static string UnknownMonitor {
            get {
                return ResourceManager.GetString("UnknownMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window class.
        /// </summary>
        public static string WindowClass {
            get {
                return ResourceManager.GetString("WindowClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window rules.
        /// </summary>
        public static string WindowRules {
            get {
                return ResourceManager.GetString("WindowRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows version incompatible.
        /// </summary>
        public static string WindowsVersionIncompatible {
            get {
                return ResourceManager.GetString("WindowsVersionIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Windows version is too old and does not support the features required to run HideMyWindows properly.
        ///For more information check out the project&apos;s README..
        /// </summary>
        public static string WindowsVersionIncompatibleText {
            get {
                return ResourceManager.GetString("WindowsVersionIncompatibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window title.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window watching method.
        /// </summary>
        public static string WindowWatchingMethod {
            get {
                return ResourceManager.GetString("WindowWatchingMethod", resourceCulture);
            }
        }
    }
}
